### ISSUE TITLE
'pip install pyanalyze' currently broken due to typeshed-client version

### ISSUE THREAD

**Issue by mthuurne** [quora/pyanalyze#190]
If I install `pyanalyze` via `pip`, it will install the latest `typeshed-client` (1.0.x) together with it. However, `pyanalyze` tries to pass a `version` argument to the `Resolver` constructor and that argument existed in 0.4.1 but doesn't exist anymore in the latest release.

In #110 the code of `pyanalyze` was updated to deal with this issue, but that fix is from a month ago while the last release of `pyanalyze` on PyPI is almost a year old. I think it would be good to either release more often, or change the README to suggest installing `pyanalyze` from Git instead of PyPI.

**Comment by JelleZijlstra** [comment]
I should get around to making a new release. I'll do it today.

**Comment by JelleZijlstra** [comment]
Just published https://pypi.org/project/pyanalyze/0.2.0/. I'm planning to do more regular releases in the future after I make some changes to improve usability for external users, such as separating out `pyanalyze_extensions` (#125) and writing more documentation.

**Comment by mthuurne** [comment]
Thanks!
