### ISSUE TITLE
Incorrect Behavior in `MultiValuedValue.get_type()`

### ISSUE THREAD

**Issue by erezsh** [quora/pyanalyze#208]
```python
>>> iv   # our variable
MultiValuedValue(vals=(SequenceIncompleteValue(typ=<class 'list'>, args=(UnresolvedValue(),), members=(UnresolvedValue(),)), KnownValue(val=[])))
>>> iv.get_type()
None
>>> iv.get_type_value()
MultiValuedValue(vals=(KnownValue(val=<class 'list'>), KnownValue(val=<class 'list'>)))
>>> iv.get_type_value().get_type()
None
```

I would expect `get_type()` to return `list`, since that is clearly the type of this node.

**Comment by JelleZijlstra** [comment]
`get_type()` is basically deprecated, since it can't be usefully implemented for a lot of Value subclasses. I haven't removed it since there are still some internal use cases I need to replace.

What are you trying to use it for? Is there some other API we could provide that would cover what you need?

**Comment by erezsh** [comment]
My needs are pretty straightforward. I need to know the type of expressions at various points in the code. For example, when there's `a * b`, or `if a`, etc., I want to know what's the type of `a` and `b`, and so on.

For now here's how my get_type function looks like:

```python
def _get_inferred_type(v):
    if isinstance(v, pyanalyze.value.MultiValuedValue):
        types = {x.val for x in v.get_type_value() .vals if isinstance(x, pyanalyze.value.KnownValue)}
        if len(types) == 1:
            t ,= types
        elif len(types) > 1:
            without_none = types - {type(None)}
            if len(without_none) == 1:
                t ,= without_none
                return Optional[t]
            else:
                return make_union(types) 
        else:
            return None
        return t

    return v.get_type()
```

If there was an interface function that took care of these details (or even some of them), with something like `get_type()`, it would make it much easier on me.

**Comment by JelleZijlstra** [comment]
So basically you want to go back to the typing object corresponding to the Value object?

What do you need the types for? If it's just to display them, `str()` on the Value object should give a reasonable representation.

**Comment by erezsh** [comment]
No, I need an actual object that I can test.

For example, for "a * b", I need different behavior for (list, int) than
(int, int). Same with +, it's different between (list, list) and (int,
int), etc.

Ideally the types would be either basic python types, or instances from the
"typing" library, since I already have code that can do issubclass on them,
like "issubclass(int, union [int, str]) returns true.

**Comment by JelleZijlstra** [comment]
Thanks for explaining!

I don't know your codebase, but I feel like the cleanest solution might be to rely on working with pyanalyze's Value objects directly, using methods like `is_value_compatible()` as the equivalent of `isinstance`. That's what pyanalyze's own type checking does.

Failing that, what you're really asking for is an API that given a Value object, returns the runtime typing.py equivalent. That's not really the kind of thing I'd like to maintain; there's all the code in `annotations.py` that does the reverse translation from runtime to Value object, and I'm not sure I'd want to have to deal with runtime typing across different Python versions any more. However, it shouldn't be hard to write something like this yourself by just casing on the different Value subclasses. They're documented at https://pyanalyze.readthedocs.io/en/latest/reference/value.html, the only part of pyanalyze that's fairly thoroughly documented so far :)

**Comment by erezsh** [comment]
Thanks for the explanation. Is `is_value_compatible()` a theoretical function that I should write, or an actual one? Because I couldn't find it.

I'm okay with a different "comparison scheme" than what I described. What I really wanted to avoid is to have to write a huge function with a long list of `isinstance` calls, and a different behavior for each Value subclass and attribute configuration. Which I'll probably have to discover with trial-and-error as I go. It's not just a lot of work, which every user would have to replicate on their own, but I don't know if I could ever be satisfied that I covered every edge case.

**Comment by JelleZijlstra** [comment]
Sorry, I meant `can_assign` (https://pyanalyze.readthedocs.io/en/latest/reference/value.html#pyanalyze.value.Value.can_assign). `is_assignable` is the easier-to-use version if you don't care about generics; `can_assign` returns a dictionary of TypeVar values.

I see where you're coming from with wanting to avoid lots of `isinstance` calls, so I'm happy to add more methods to `Value` in general; I just don't think "runtime type" is going to be a good concept to expose. There are already some useful helper functions like https://pyanalyze.readthedocs.io/en/latest/reference/value.html#pyanalyze.value.unite_values

**Comment by JelleZijlstra** [comment]
Closing as we're instead moving to get rid of `get_type()`.
