### ISSUE TITLE
Consider replacing long-deprecated `imp` module with modern `importlib`

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#210]
Thanks for your work on this! Running pyanalyze produced a `DeprecationWarning` due to using the standard library `imp` module in [pyanalyze/name_check_visitor.py](https://github.com/quora/pyanalyze/blob/master/pyanalyze/name_check_visitor.py), which has bee [deprecated since Python 3.4 in favor of importlib](https://docs.python.org/3/library/imp.html). Can it be replaced with the modern [`importlib`](https://docs.python.org/3/library/importlib.html#module-importlib) (especially now that Python 2 support has been dropped)? Thanks!

**Comment by JelleZijlstra** [comment]
Thanks for flagging this; I rewrote `importer.py` a while ago to avoid using imp but missed this one.

**Comment by CAM-Gerlach** [comment]
Thanks for the quick fix @JelleZijlstra !
