### ISSUE TITLE
Allow disabling specific checks with --enable-all and add corresponding --disable-all flag

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#211]
Currently, codes can be additively enabled and disabled on top of the default config with the `-e` and `-d` CLI options. However, when `--enable-all` is passed, `-d` is ignored. It would be very useful to be able enable all codes except for the specified ones, without the tedious and fragile alternative of manually specifying every default-disabled code with `-e`. This is easy to accomplish by simply moving [lines 338-342](https://github.com/quora/pyanalyze/blob/ba3e5882a1abbb02cf95cd6747bb617a979e0128/pyanalyze/node_visitor.py#L334) up a level in `node_visitor.py`.

Equally, it would be useful to very useful to support being able to only enable specific specific listed codes, e.g. with a `--disable-all` argument, in concert with the change. Again, this would be simple to add, just add another branch to the if above plus the arg itself. It could either be made exclusive with `--enable-all`, or could override it (as duplicate codes with `-e` currently does with `-d`).

Given its simple to do, I'd be happy to submit a PR to this effect. Thanks!

**Comment by JelleZijlstra** [comment]
Good idea! I'd be happy to accept a PR making these changes.

**Comment by CAM-Gerlach** [comment]
Thanks, will do!
