### ISSUE TITLE
Pyanalyze raises ModuleNotFoundError and prints traceback on absolute or relative imports of local Python modules that aren't on sys.path

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#218]
I'm running Pyanalyze against my test suite as well as my production code, with the latter is a separate directory outside my installed package (per the recommendations of the `src` layout), and not installed itself, but with `__init__.py` in every directory all the way up to and including the root `tests` dir. As such, Pyanalyze should be able to determine (with pkgutil/etc) that the given file lies within a Python package, and perform the import accordingly; however, this doesn't work even if I specify the top-level package explicitly as the path argument to the pyanalyze CLI, nor even changing the working directory to the top-level package dir.

However, Pyanalyze fails to successfully handle both absolute imports, as tested on the latest `master`, with the error you'd expect:

<details>

```python-traceback
Traceback (most recent call last):
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\name_check_visitor.py", line 812, in _load_module
    return self.load_module(self.filename)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\name_check_visitor.py", line 832, in load_module
    return importer.load_module_from_file(filename)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\importer.py", line 98, in load_module_from_file
    return import_module(str(abspath), abspath), False
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\importer.py", line 106, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpaceX\submanager\tests\functional\test_validate.py", line 17, in <module>
    from tests.functional.conftest import (
ModuleNotFoundError: No module named 'tests.functional'
```

</details>

and relative imports, with an error message that further indicates that something isn't correctly handling spaces in the path (from a username I created a decade ago when I didn't know better, unfortunately):

<details>

```python-traceback
Traceback (most recent call last):
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\name_check_visitor.py", line 812, in _load_module
    return self.load_module(self.filename)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\name_check_visitor.py", line 832, in load_module
    return importer.load_module_from_file(filename)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\importer.py", line 98, in load_module_from_file
    return import_module(str(abspath), abspath), False
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\importer.py", line 106, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpaceX\submanager\tests\functional\test_validate.py", line 17, in <module>
    from .conftest import (
ModuleNotFoundError: No module named 'C:\\Users\\C'
```

</details>

What's more, while this would be tolerable as the analysis still works quite well and I use local test imports very sparingly in my tests (only to import common types, essentially), while I can silence the Pyanalyze message (by putting `# static analysis: ignore[import_failed]` as an inline comment on the first non-blank line of the file, which is rather awkward to do but possible), there appears to be no way to silence the long traceback that prints for every file and module that failed importing, making the output essentially useless.

Therefore, the only way currently to use a wrapper script to temporarily add the `tests` dir to `sys.path`, run `pyanalyze`, and then restore `sys.path` to the original value, or else not run pyanalyze on those files at all.

At the very least, can the error be properly suppressed, and ideally `pyanalyze` correctly handle local imports from modules in packages? Or any other ideas to resolve this? Thanks!

**Comment by JelleZijlstra** [comment]
Thanks for reporting this! The core of the issue here is that pyanalyze relies heavily on being able to import the code it analyzes, and currently to import something it must be on sys.path. So I would in fact recommend running it as something like `PYTHONPATH=. python -m pyanalyze tests/`.

But obviously that's not always a good user experience. I actually made a change a while ago (#122) that made pyanalyze more in control of its own importer, and it strikes me that maybe it doesn't need to rely on `sys.path` at all any more: instead we could provide a command-line flag that controls the sys.path being used at https://github.com/quora/pyanalyze/blob/master/pyanalyze/importer.py#L34. I'll have to play around with that to see whether that's feasible. You also hinted that https://docs.python.org/3/library/pkgutil.html could help make this easier, so I'll look into that.

**Comment by CAM-Gerlach** [comment]
Thanks for your ultra-fast and kind response!

> The core of the issue here is that pyanalyze relies heavily on being able to import the code it analyzes

Yup, I'd figured this much based on the output and our discussion in #216 .

> So I would in fact recommend running it as something like `PYTHONPATH=. python -m pyanalyze tests/`.

Ah, that's a much quicker oneliner than a wrapper script; I thought about using Pythonpath but forgot about setting env variables for single scripts like that.

Ideally, this wouldn't be needed, but its not that terrible for now (since I use a `src` layout), However, as a low-hanging fruit, at the very least you should suppress the traceback that still gets printed even when the `import_error` is suppressed, as there will be plenty of situations where modules will be unimportable but the user still wants a best-effort type check, and while being able to handle that is ideal, its not a trivial problem to solve, while at least suppressing the error is a useful stopgap.

**Comment by JelleZijlstra** [comment]
> at the very least you should suppress the traceback that still gets printed even when the import_error is suppressed

Good point, that's actually a really easy change to make. I submitted #220.

**Comment by CAM-Gerlach** [comment]
@JelleZijlstra Also, this can be avoided by the user simply running it as `python -m pyanalyze` (which was the only way offered prior to v0.3.0, and thus possibly why you didn't see this pop up as an issue before), since Python adds the CWD to the PATH by default, which works cross-platform and without shell tricks.
