### ISSUE TITLE
Pyanalyze doesn't exit non-zero when errors are found

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#224]
Unlike all other linters I'm aware of, Pyanalyze doesn't exit non-zero when errors are found, or even have an option to do so, making it unusable in any workflows (pre-commit hooks, CIs, shell scripts, etc) that expect this. The `main()` classmethod of `NodeCheckVisitor` does return a bare `int` that would correspond to an error code, but its not actually passed to `sys.exit`, so it has no effect when running from the CLI, the context in which it is most immediately useful.

To fix this, we can simply wrap [the `NameCheckVisitor,main()` call in `__main__,py`](https://github.com/quora/pyanalyze/blob/ea6b66c3514cee163ab6bae076293d61d008a0f7/pyanalyze/__main__.py#L5) in `sys.exit()`, and everything will behave as expected. I'll submit a PR to that effect momentarily. It would be great if you could cut a v0.3.1 release soon with this change, as otherwise I can't use pyanalyze with either pre-commit or CIs (two of the three main contexts you'd want to use a linter) without writing a bespoke wrapper script (which would swiftly be rendered obsolete). Thanks!

**Comment by JelleZijlstra** [comment]
Thanks for catching that! I will release 0.3.1 in a moment, going to wait for some internal checks to run.

**Comment by CAM-Gerlach** [comment]
Thanks!
