### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erezsh** [quora/pyanalyze#272]
Seems like there have been a lot of improvements lately, but the last release is from Aug 12, over 3 months ago.

Are there any plans to make a new release soon?

(no pressure, I'll work off master if necessary, but I prefer to wait for a release if it's coming soon)

**Comment by JelleZijlstra** [comment]
Yeah I'll cut another release today. I am probably going to continue more intensive work for a while, but I can always make another release.

**Comment by erezsh** [comment]
Cool, thanks!

**Comment by JelleZijlstra** [comment]
https://pypi.org/project/pyanalyze/0.4.0/#description

**Comment by erezsh** [comment]
Just a quick note, it isn't mentioned in the notes but `pyanalyze.value.UnresolvedValue` is no longer available. fwiw I replaced it in my code with `AnyValue` and it works for my purposes.

**Comment by JelleZijlstra** [comment]
Oh yes, I didn't mention that as explicitly because there was only meant to be one instance of the class. Added it in #274.
