### ISSUE TITLE
AssertionError: invalid argspec BoundMethodArgSpecWrapper

### ISSUE THREAD

**Issue by dimaqq** [quora/pyanalyze#5]
```py
Traceback (most recent call last):
  File "/v/site-packages/pyanalyze/name_check_visitor.py", line 705, in visit
    ret = method(node)
  File "/v/site-packages/pyanalyze/name_check_visitor.py", line 2843, in visit_Subscript
    return_value, _ = self._get_argspec_and_check_call(
  File "/v/site-packages/pyanalyze/name_check_visitor.py", line 3372, in _get_argspec_and_check_call
    extended_argspec = self._get_argspec_from_value(callee_wrapped, node)
  File "/v/site-packages/pyanalyze/name_check_visitor.py", line 3465, in _get_argspec_from_value
    return self._get_argspec(callee_wrapped.val, node, name=name)
  File "/v/site-packages/pyanalyze/name_check_visitor.py", line 3495, in _get_argspec
    return self.arg_spec_cache.get_argspec(obj, name=name, logger=self.log)
  File "/v/site-packages/pyanalyze/arg_spec.py", line 1124, in get_argspec
    argspec = self._cached_get_argspec(obj, kwargs)
  File "/v/site-packages/pyanalyze/arg_spec.py", line 1136, in _cached_get_argspec
    extended = self._uncached_get_argspec(obj, kwargs)
  File "v/site-packages/pyanalyze/arg_spec.py", line 1161, in _uncached_get_argspec
    return BoundMethodArgSpecWrapper(argspec, KnownValue(obj.__self__))
  File "/v/site-packages/pyanalyze/arg_spec.py", line 142, in __init__
    assert isinstance(argspec, ExtendedArgSpec), "invalid argspec %r" % (argspec,)
AssertionError: invalid argspec BoundMethodArgSpecWrapper(
  argspec=ExtendedArgSpec(
    _has_return_value=False,
    arguments=[Parameter(default_value=<object object at 0x7fa6a833f990>, name='self', typ=None)],
    implementation=None,
    kwargs='kwargs',
    kwonly_args=None,
    name='GenericAlias',
    params_of_names={
      'self': Parameter(default_value=<object object at 0x7fa6a833f990>, name='self', typ=None),
      'args': Parameter(default_value=<object object at 0x7fa6a833f990>, name='args', typ=TypedValue(typ=<class 'tuple'>)),
      'kwargs': Parameter(default_value=<object object at 0x7fa6a833f990>, name='kwargs', typ=TypedValue(typ=<class 'dict'>))},
    return_value=UnresolvedValue(), starargs='args'),
    self_value=TypedValue(typ=<class 'types.GenericAlias'>))

Internal error: AssertionError(-"-) (code: internal_error)
```

I'm sorry the code is closed-source, I could try to track it down somehow...
I get this error using `Python 3.9.0b1` but not 3.8

**Comment by JelleZijlstra** [comment]
I guess that means it's trying to make a bound method of something that's already a bound method? It should show the line of code that triggers the error, would you be able to share that line?

**Comment by dimaqq** [comment]
I think the line is this:
`self.register_queue: Queue[List[RegistrationItem]] = Queue()`
it's part of `__init__` and `Queue` is `queue.Queue`

**Comment by JelleZijlstra** [comment]
What Python version are you on (including the patch version)?

**Comment by dimaqq** [comment]
> I get this error using `Python 3.9.0b1` but not 3.8

**Comment by dimaqq** [comment]
Full MRE:

```py
from queue import Queue
from typing import List

class I:
    ...

class X:
    def __init__(self):
        self.q: Queue[List[I]] = Queue()
```

mypy tells me that I have `error: syntax error in type comment`, perhaps I can't type 😮 

pyanalyze gives off a traceback `AssertionError: invalid argspec BoundMethodArgSpecWrapper(argspec=ExtendedArgSpec(_has_return_value=False, arguments=[Parameter(default_value=<object object at 0x7f8c801cf990>, name='self', typ=None)], implementation=None, kwargs='kwargs', kwonly_args=None, name='GenericAlias', params_of_names={'self': Parameter(default_value=<object object at 0x7f8c801cf990>, name='self', typ=None), 'args': Parameter(default_value=<object object at 0x7f8c801cf990>, name='args', typ=TypedValue(typ=<class 'tuple'>)), 'kwargs': Parameter(default_value=<object object at 0x7f8c801cf990>, name='kwargs', typ=TypedValue(typ=<class 'dict'>))}, return_value=UnresolvedValue(), starargs='args'), self_value=TypedValue(typ=<class 'types.GenericAlias'>))`

**Comment by JelleZijlstra** [comment]
The mypy issue is an unrelated bug that will be fixed in the next mypy release (the AST for subscripts was changed and mypy got confused about it).

**Comment by JelleZijlstra** [comment]
Also thanks for the detailed report! I don't have time right now to look in more detail but I'll fix this.

**Comment by JelleZijlstra** [comment]
#7 should fix this.
