### ISSUE TITLE
How can I just run this thing on a string?

### ISSUE THREAD

**Issue by geajack** [quora/pyanalyze#592]
This library looks useful, but I just have some Python code in a string. How can I just run this tool on that code and get back the results? Specifically I'd like to just get back the list of "Failure" objects that the main code seems to produce.

**Comment by geajack** [comment]
In the mean time, for anyone else, this more-or-less works:

```
from pyanalyze.error_code import ErrorCode
from pyanalyze.checker import Checker
from pyanalyze.name_check_visitor import NameCheckVisitor
import ast

code = """print(a)"""
tree = ast.parse(code)

visitor = NameCheckVisitor("x.py", code, tree, checker=Checker())
visitor.check()
failures = visitor.all_failures

for failure in failures:
    print(failure)
```

You have to make a dummy `x.py` file in the same directory with nothing in it, and the script will put output in `stderr` which can be kind of annoying, but you do get the information back.

**Comment by ambi88dex** [comment]
> In the mean time, for anyone else, this more-or-less works:
> 
> ```
> from pyanalyze.checker import Checker
> from pyanalyze.name_check_visitor import NameCheckVisitor
> import ast
> 
> code = """print(a)"""
> tree = ast.parse(code)
> 
> visitor = NameCheckVisitor("x.py", code, tree, checker=Checker())
> visitor.check()
> failures = visitor.all_failures
> 
> for failure in failures:
>     print(failure)
> ```
> 
> You have to make a dummy `x.py` file in the same directory with nothing in it, and the script will put output in `stderr` which can be kind of annoying, but you do get the information back.

I was thinking to propose a similar solution but already found this one!
