### ISSUE TITLE
Question on reusing real types in annotations

### ISSUE THREAD

**Issue by dimaqq** [quora/pyanalyze#6]
Consider this code:

```py
from collections.abc import AsyncIterable


async def agen_things() -> AsyncIterable[str]:
    yield "xx"
```

`mypy` is happy with it, but `pyanalyze` reports a traceback `TypeError: 'ABCMeta' object is not subscriptable`

**Comment by JelleZijlstra** [comment]
This also errors at runtime (unless you have `from __future__ import annotations` on, or maybe if you're on 3.9). Mypy allows it because the class is marked as generic in typeshed, but pyanalyze looks at the runtime type.

It already accepts this type if you quote it:
```
$ python -m pyanalyze tmp.py 

value: GenericValue(typ=<class 'collections.abc.AsyncIterable'>, args=(TypedValue(typ=<class 'str'>),)) (code: inference_failure)
In tmp.py at line 5:
   2: from pyanalyze import dump_value
   3: 
   4: async def agen_things(x: "AsyncIterable[str]") -> "AsyncIterable[str]":
   5:     dump_value(x)
          ^
   6:     yield "xx"
```

**Comment by JelleZijlstra** [comment]
I added a basic test for `from __future__ import annotations` in #8. Let me know if you see any more issues.
