### ISSUE TITLE
Unable to install on Windows 11

### ISSUE THREAD

**Issue by Alurith** [quora/pyanalyze#632]
I am unable to install pyanalyze on Windows 11 with python 3.10.6, I tried both with pip and poetry and I've got two distinct errors.

Here gist with both outputs: [https://gist.github.com/Alurith/23fce0729b6da35f62fc1803e09104b7](https://gist.github.com/Alurith/23fce0729b6da35f62fc1803e09104b7)

**Comment by JelleZijlstra** [comment]
Thanks, seems like this is due to the `qcore` dependency. Just to get a more focused error, could you try `pip install qcore` directly and share the output.

**Comment by Alurith** [comment]
@JelleZijlstra sure, I've updated the gist with the `pip install qcore` output [https://gist.github.com/Alurith/23fce0729b6da35f62fc1803e09104b7](https://gist.github.com/Alurith/23fce0729b6da35f62fc1803e09104b7)

**Comment by JelleZijlstra** [comment]
Thanks! Probably the easiest solution is going to be for us to provide wheels for qcore on 3.10 and Windows, currently it only provides 3.6 through 3.9: https://pypi.org/project/qcore/#files.

If you happen to have 3.9 or lower around, could you check whether that works? If so, I will look into making a new release of qcore (and probably also asynq) that provides 3.10/3.11 wheels.

**Comment by Alurith** [comment]
It works with Python 3.9.2

**Comment by JelleZijlstra** [comment]
quora/qcore#94

**Comment by JelleZijlstra** [comment]
I released asynq 1.5.0 and qcore 1.9.0 with 3.10 and 3.11 wheels. Please try again and let me know if you're still seeing issues.

**Comment by Alurith** [comment]
I've tried with Python 3.10 and it worked! Thanks!

**Comment by JelleZijlstra** [comment]
Thanks for confirming!
