### ISSUE TITLE
White list possibility on `pyproject.toml`

### ISSUE THREAD

**Issue by mflova** [quora/pyanalyze#648]
First, congrats for the tool! I have just found about it and it is a tool that can detect unique stuff.

Right now, many tools or linters share many features in common. Therefore, for some specific tools I like disabling all checks and enabling the ones I want one by one by doing:

```python
python3 -m pyanalysis --disable-all --enable [...]
```

Is there a possibility of doing this but with `pyproject.toml`? Right now, the only possibility seems to be copy-pasting all rules, set them to `false` and then switching to `true` only the ones you want. Is there a kewyord like `only_rules` that I can use in `pyproject.toml`? Thanks!

A quick off-topic question. Why `pyproject.toml` is not automatically read as any other tool (`flake8`, `mypy`, `ruff`...)? Why is it neded to provide `--config-file` flag?

**Comment by JelleZijlstra** [comment]
Thanks! I agree that a config file option to disable all but a few rules could be helpful. Do other tools have similar functionality? That could guide the design we choose here.

One option could be to support `disable_all = true` in the TOML file, mirroring the command-line interface. Then you could have a config file like
```
disable_all = true
duplicate_yield = true
```
To enable only `duplicate_yield`.

> Why pyproject.toml is not automatically read as any other tool (flake8, mypy, ruff...)? Why is it neded to provide --config-file flag?

Yes, would be better if we picked up pyproject.toml automatically; I didn't think of that when adding config file support.

**Comment by mflova** [comment]
That would be great! I will try to take a look in the future to see if I can easily implement it. Thank you for your reply!

**Comment by mflova** [comment]
Now that I have more time, I wanted to start contributing a littel bit!

About the `pyproject.toml`, All the tools I have used so far that are `pyproject` compatible (`mypy`, `flake8`, `black`, `pytest`...) they all auto-detect the file. In fact, I was assuming that it would be the same for this tool and it took me some time to realize that you have to indicate it explicitely.

About the white list feature, I have been thinking and so far two solutions came to my mind:

- The approach that you mentioned. Similar to what CLI does. In this approach, the presence of `disable-all` at any position will automatically allow choosing the rules you want to activate.
- The second approach would be having a specific keyword (the kind of `only_enable_rules`, `white_list_rules`...) that would contain a list-type object with the names of all enabled rules. If this keyword is present, all the other rules that might appear outside could be ignored or a warning could be raised to tell the user that these have no effect.

In my opinion, second approach is easier to see at first sight. But both could work of course. Since you are the main author, I would also like to know your opinion regarding which one could be easier to maintain or which one could have less changes regarding potential refactors.

**Comment by JelleZijlstra** [comment]
Great! I'd love for you to contribute.

I think either way of implementing this could work. Your second proposed approach feels less consistent to me because currently an error code is enabled/disabled only by setting `error_code = true` or false in the config file, and your approach would instead add a list form that also influences whether the error code is on or off.

(I saw you edited away the bit about automatically picking up pyproject.toml. It's indeed out of scope for this issue, but I do agree we should do that. Feel free to open a separate issue or PR.)

**Comment by mflova** [comment]
Yes! I edited the comment as I missread before. I will create a separate issue for that.

I agree with your feedback. I will start reading how the project is structured and eventually I will create a PR :)
